import { createLazyFileRoute} from "@tanstack/react-router"; //<-- React Router
import { LoginForm } from "@/features/auth/components/login-form"; //login form that we created
import { TitleHeader } from "@/features/auth/components/title-header";
import { AuthCard } from "@/features/auth/components/auth-card";

export const Route = createLazyFileRoute("/_auth/auth/login")({ //custom lazy route generated by tanstack router.
  component: RouteComponent,
});

function RouteComponent() { //<-- what the route contains.
  return (
    <div className="min-h-screen bg-slate-900 text-white flex flex-col items-center justify-center space-y-8 px-4">
      <TitleHeader />
      <AuthCard
        title="Login"
        description="Enter your details to login to your account."
        footerText="Don't have an account?"
        footerLink={{ text: "Register", to: "/auth/register" }}
      >
        <LoginForm />
      </AuthCard>
    </div>
  );
}
